deployr2/urls.py
from django.conf.urls import url, patterns

from deployr2 import views

urlpatterns = patterns('',
   url(r'^$', views.index, name='index'),
   url(r'^start_deployment/$', views.start_deployment, name='start_deployment'),
   url(r'^get_builds$', views.get_builds_for_build_type_and_branch),
   url(r'^deployments/(?P<deployment_name>[\da-f-]+)/$', views.get_deployment, name='deployment'),
   url(r'^deployments/(?P<deployment_name>[\da-f-]+)/delete$', views.delete_deployment, name='delete_deployment'),
)

techdev/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'techdev.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('deployr2.urls', namespace="deployr2"))
)

deployr2/models.py
from django.db import models

# Create your models here.


class Deployment(models.Model):
    id = models.CharField(max_length=36, primary_key=True)
    create_date = models.DateTimeField()
    # TODO backend, frontend branch
    # TODO backend, frontend build
    # TODO status. Or should we always get this from docker?
    # TODO creator

deployr2/views.py
import json
import logging
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from file_preparer import FilePreparer
from teamcity import Teamcity
from models import Deployment

teamcity = Teamcity()
logger = logging.getLogger(__name__)


def index(request):
    deployments = Deployment.objects.all()
    return render(request, 'deployr2/index.html', {'deployments': deployments})


def start_deployment_form(request, error=None):
    backend_branches = teamcity.get_branches('Techdev_TrackrBackend')
    frontend_branches = teamcity.get_branches('Techdev_TrackrFrontend')
    model = {
        'backend_branches': backend_branches,
        'frontend_branches': frontend_branches,
        'error': error
    }
    return render(request, 'deployr2/start_deployment.html', model)


def start_deployment_post(request):
    try:
        backend_branch = request.POST['backend_branch']
        frontend_branch = request.POST['frontend_branch']
        backend_build_id = request.POST['backend_build_id']
        frontend_build_id = request.POST['frontend_build_id']
    except KeyError, e:
        return start_deployment_form(request, error=e.message)

    from uuid import uuid4
    deployment_name = str(uuid4())
    logger.info('Creating deployment %', deployment_name)

    file_preparer = FilePreparer(deployment_name)
    file_preparer.create_directory_structure()

    backend_artifact = ''
    # download artifacts from teamcity into folder
    for artifact in teamcity.get_artifacts(backend_build_id):
        # TODO hack, the backend artifact name should not be from here!
        if artifact.name.endswith('jar'):
            backend_artifact = artifact.name
        res = teamcity.stream_artifact(artifact.content_link)
        file_preparer.download_backend_artifact(res.raw, artifact.name)

    for artifact in teamcity.get_artifacts(frontend_build_id):
        res = teamcity.stream_artifact(artifact.content_link)
        file_preparer.download_frontend_artifact(res.raw, artifact.name)

    # prepare files index.html <base tag>
    # create docker container
    from docker import Client
    c = Client('unix://var/run/docker.sock')

    backend_container = c.create_container(image='java:openjdk-8', command='java -jar ' + backend_artifact, detach=True, name='backend_' + deployment_name, volumes=['/opt/trackr-backend'],
                                           working_dir='/opt/trackr-backend')
    c.start(backend_container['Id'], binds={'/opt/techdev/deployr2/deployments/%s/backend' % deployment_name: {'bind': '/opt/trackr-backend', 'ro': True}})

    frontend_container = c.create_container(image='nginx', ports=[80], name='frontend_' + deployment_name, volumes=['/etc/nginx/conf.d/default.conf', '/usr/share/nginx/html'])
    c.start(frontend_container['Id'], links=[('backend_' + deployment_name, 'backend')], publish_all_ports=True, binds={
        '/opt/techdev/deployr2/default.conf': {'bind': '/etc/nginx/conf.d/default.conf', 'ro': True},
        '/opt/techdev/deployr2/deployments/%s/frontend/www' % deployment_name: {'bind': '/usr/share/nginx/html', 'ro': True}
    })

    inspect = c.inspect_container('frontend_' + deployment_name)
    frontend_port = inspect['NetworkSettings']['Ports']['80/tcp'][0]['HostPort'] # Help!!!

    # create an entity so we know of this deployment later
    from django.utils import timezone
    deployment = Deployment(id=deployment_name, create_date=timezone.now())
    deployment.save()

    import augeas
    a = augeas.Augeas(root='/')
    a.defvar('host', '/files/etc/apache2/sites-available/deployr.conf')
    a.defnode('newloc', '$host/VirtualHost/Location[last() + 1]', '')
    a.set('$newloc/arg', '/' + deployment_name)
    a.set('$newloc/directive', 'ProxyPass')
    a.set('$newloc/*[self::directive="ProxyPass"]/arg[1]', 'http://localhost:' + frontend_port)
    a.save()

    return HttpResponseRedirect(reverse('deployr2:deployment', kwargs={'deployment_name': deployment_name}))


def start_deployment(request):
    if request.method == 'GET':
        return start_deployment_form(request)
    elif request.method == 'POST':
        return start_deployment_post(request)


def get_builds_for_build_type_and_branch(request):
    # TODO required parameters!
    branch = request.GET.get('branch')
    build_id = request.GET.get('build_id')
    builds = teamcity.get_builds(build_id, branch)
    return HttpResponse(json.dumps([build.__dict__ for build in builds]), content_type="application/json")


def get_deployment(request, deployment_name):
    deployment = Deployment.objects.get(id=deployment_name)
    return render(request, 'deployr2/deployment.html', {'deployment': deployment})


def delete_deployment(request, deployment_name):
    deployment = Deployment.objects.get(id=deployment_name)

    # confirm docker containers are stopped
    # remove docker containers inclusive volumes

    # remove folders
    import shutil
    from django.conf import settings
    shutil.rmtree(settings.DEPLOYR2_DEPLOYMENTS + deployment.id)

    # remove entity
    deployment.delete()

    return HttpResponseRedirect(reverse('deployr2:index'))

deployr2/templates/deployr2/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>deployr2</title>
    <link rel="stylesheet" href="{% static "deployr2/css/normalize.css" %}"/>
    <link rel="stylesheet" href="{% static "deployr2/css/skeleton.css" %}"/>
    <link rel="stylesheet" href="{% static "deployr2/css/main.css" %}"/>
    {% block css %}{% endblock %}
    {% block javascript %}{% endblock %}
</head>
<body>
<div class="container">
    <div class="row">
        <div class="four columns"><h1>deployr2</h1></div>
        <div class="three columns"><img class="img-responsive" src="http://techdev.de/assets/img/logo1-techdev.png" alt="techdev logo"/></div>
    </div>
    {% block content %}{% endblock %}
</div>
</body>
</html>

deployr2/templates/deployr2/deployment.html
{% extends 'deployr2/base.html' %}
{% block content %}
    <h3>{{ deployment.id }}</h3>
    <div class="row">
        <div class="columns twelve">
            <a class="button" href="/{{ deployment.id }}">Goto deployment</a>
            <p>The deployment is RUNNING</p>
        </div>
    </div>
    <div class="row">
        <div class="columns six">
            <h5>Actions</h5>

            <form action="stop" method="post">
                {% csrf_token %}
                <button type="submit" class="stop">Stop</button>
            </form>

            <form action="{% url 'deployr2:delete_deployment' deployment.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="delete">Delete</button>
            </form>
        </div>
    </div>

{% endblock %}

deployr2/templates/deployr2/index.html
{% extends 'deployr2/base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deployr2/css/index.css' %}"/>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="four columns">
            <h2>Welcome!</h2>
            <p>This is deployr2, the deployment app for techdev. Test out feature branches with the ease of a few clicks!</p>
        </div>
        <div class="eight columns">
            <h2>Start a new deployment</h2>
            <p>From here you can start a new deployment to our QS server.</p>
            <p>
                <a class="button" href="{% url 'deployr2:start_deployment' %}">Go &gt;&gt;</a>
            </p>
        </div>
    </div>

    <h2>Running deployments</h2>
    <div class="row">
    {% for deployment in deployments %}
        <div class="columns four deployment">
            <h5>Deployment {{ forloop.counter }}</h5>
            <p>Status: RUNNING (TODO should also have STOPPED)</p>
            <p>Branches: TODO</p>
            <a class="button" href="/{{ deployment.id }}">Goto</a>
            <a class="button inspect" href="{% url 'deployr2:deployment' deployment.id %}">Inspect</a>
            <a class="button stop" href="STAHP">Stop</a>
        </div>

        {% if forloop.counter|divisibleby:"3" %}
            </div><div class="row">
        {% endif %}
    {% endfor %}
    </div>

{% endblock %}

deployr2/templates/deployr2/start_deployment.html
{% extends 'deployr2/base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static "deployr2/css/start_deployment.css" %}"/>
{% endblock %}

{% block javascript %}
    <script src="{% static 'deployr2/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'deployr2/js/knockout-3.2.0.js' %}"></script>

    <script type="text/javascript" src="{% static 'deployr2/js/start_deployment.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="columns 12">
            <h2>Start a new deployment</h2>
            <p>Please choose a backend and frontend branch and build number, then press GO.</p>
        </div>
    </div>

    <div class="row">
        <div class="columns five">
            {% if error %}
                <p class="error">Parameter missing: {{ error }}</p>
            {% endif %}
        </div>
    </div>

    <form class="hidden-radios" action="{% url 'deployr2:start_deployment' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="columns five">
                <h4>trackr-backend</h4>
                <select name="backend_build_id" data-bind="options: backendBuilds, optionsText: 'number', optionsValue: 'id'"></select>
                {% for branch in backend_branches %}
                    <input id="backend-{{ branch.name }}" type="radio" name="backend_branch" value="{{ branch.name }}"/>
                    <label class="branch-radio" for="backend-{{ branch.name }}">{{ branch.name }}</label>
                {%  endfor %}
            </div>

            <div class="columns five">
                <h4>trackr-frontend</h4>
                <select name="frontend_build_id" data-bind="options: frontendBuilds, optionsText: 'number', optionsValue: 'id'"></select>
                {% for branch in frontend_branches %}
                    <input id="frontend-{{ branch.name }}" type="radio" name="frontend_branch" value="{{ branch.name }}"/>
                    <label class="branch-radio" for="frontend-{{ branch.name }}">{{ branch.name }}</label>
                {%  endfor %}
            </div>
        </div>

        <div class="columns two">
            <button>Go &gt;&gt;</button>
        </div>
    </form>
{% endblock %}